# Use the official Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

# Install any needed dependencies specified in requirements.txt
RUN python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt


# Copy the Flask application code to the container
COPY . .

# Set the FLASK_APP environment variable
ENV FLASK_APP=app.py

# Expose the port Flask is running on
EXPOSE 5000

# Run the Flask application
CMD ["flask", "run", "--host=0.0.0.0"]
